services:
  - type: web
    name: counseling-app
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install && npm install --prefix ../client && npm run build --prefix ../client"
    startCommand: "npm start"